# Generated by Django 3.0.8 on 2020-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
