# Generated by Django 3.0.8 on 2020-09-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_auto_20200919_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
