# Generated by Django 3.0.8 on 2020-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_auto_20200919_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
